### ISSUE TITLE
Print receipt with left indent

### ISSUE THREAD

**Issue by portugaAndre** [moezbaccouche/react-native-pax-library#3]
Hello there! 
I'm trying to center a text in the receipt, I've noticed that they use left indent for that. 
Is there anyway of using it in your lib?
Also how do you bold a text?

**Comment by moezbaccouche** [comment]
Hi Andre, 
Unfortunatly to benfit from advanced ticket shaping such as text styling and printing images we have to make use of other PAX native libraries to print tickets as bitmaps that I don't have the right to share publically due to author's copyrights. However for the indent you can try to implement a function on the React-Native part in which you can position the text depending on the ticket width.

I'm going to show you an example of a function that I created myself that prints two words on the same line. The first word is located on the left side of the ticket and the second word on the extreme right side.

For this example I'm using an 80/70 thermal paper which is 48 characters width.
I hope that this code snippet will help create your own function.

```js
const getOverviewLine = (wordLeft, wordRight) => {
  const nbSpaces = TICKET_MAX_WIDTH - (wordLeft.length + wordRight.length);
  let spacesBetweenWords = "";
  for (let i = 0; i < nbSpaces; i++) {
    spacesBetweenWords += " ";
  }

  return wordLeft + spacesBetweenWords + wordRight;
};
```

**Comment by portugaAndre** [comment]
Thank you a lot. 
I appreciated it.
